language: en_US
license: "Put your license here"
#########################################################################
#                       Database Config                                 #
#########################################################################
MySQL:
  Enable: false                  #if false, SQLite will be used.
  Database: "TelegramLogin"
  Username: "TelegramLogin"
  Password: "YourPassword"
  Host: "localhost"
  Port: 3306
  SSL: false

bungee: false   #Enable if you are running inside a network (remember, place this plugin in bungeecord plugins too)

#########################################################################
#                       Bot Config                                      #
#########################################################################
bot:
  name: "@YourBotName"
  token: "YourToken"    #recover it from @BotFather

#########################################################################
#                          2FA Section                                  #
#########################################################################
2FA:
  enabled: false  #if false plugin will be used as primary login system (disabling every commands)
                  #if true you will be able to execute commands in "allowedCommands"
  allowed-commands:
    - "/login"
    - "/register"
