name: TelegramLogin
main: it.ivirus.telegramlogin.TelegramLogin
author: iVirus
version: ${project.version}
api-version: 1.13
commands:
  telegramlogin:
    description: main command
    aliases: [tlogin]